# Generated by Django 2.1.5 on 2019-02-07 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 11, 39, 42, 966697), verbose_name='date published'),
        ),
    ]
