# Generated by Django 2.1.5 on 2019-02-07 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190207_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 12, 7, 52, 706305), verbose_name='date published'),
        ),
    ]
